# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: The Dyvil Blog
email: clashsoft@hotmail.com
description: >
  This is the official Dyvil update blog! You can expect Update Summaries of the language every few releases as well as
  interesting articles, observations and rants about the design and implementation process.
  This website is currently under development.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://dyvil.github.io" # the base hostname & protocol for your site
twitter_username: clashsoft
github_username:  dyvil

# Build settings
markdown: kramdown

google_analytics:
show_downloads: true
theme: jekyll-theme-dinky
